pluginGroup = com.shuzijun.leetcode
pluginName = leetcode-editor
pluginVersion = 9.0
gradleVersion = 9.6.1
kotlin.stdlib.default.dependency = false

pluginSinceBuild = 262.0
pluginUntilBuild =
pluginDescription = doc/description.html

platformType = IU
platformVersion = 2026.2

# ,-Dide.browser.jcef.log.level=verbose,-Duser.language=en-US
runIdeJvmArgs = -Dfile.encoding=utf-8
